# Generated by Django 4.2.23 on 2025-07-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0008_remove_student_board1_remove_student_board2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ph',
        ),
    ]
