# Generated by Django 4.2.23 on 2025-07-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0009_remove_student_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='srsapp.subjects'),
        ),
    ]
