# Generated by Django 4.2.23 on 2025-07-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0007_student_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='board1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='board2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cadd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fmarks1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fmarks2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='income',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ocp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='padd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pyear1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pyear2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects_id',
        ),
    ]
