# Generated by Django 5.2.4 on 2025-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
