# Generated by Django 5.2.4 on 2025-08-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_course_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDailyAttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='attendance.sectiondailyattendance')),
            ],
            options={
                'unique_together': {('attendance', 'hour')},
            },
        ),
        migrations.DeleteModel(
            name='ClassStudent',
        ),
    ]
