# Generated by Django 5.2.4 on 2025-08-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_timetableslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='subject',
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_hours', models.PositiveIntegerField(default=0)),
                ('tuesday_hours', models.PositiveIntegerField(default=0)),
                ('wednesday_hours', models.PositiveIntegerField(default=0)),
                ('thursday_hours', models.PositiveIntegerField(default=0)),
                ('friday_hours', models.PositiveIntegerField(default=0)),
                ('classIns', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='attendance.class')),
            ],
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.DeleteModel(
            name='TimetableSlot',
        ),
    ]
