# Generated by Django 5.2.4 on 2025-08-12 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_timetableslot_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sectionschedule',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='friday_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='monday_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='thursday_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='tuesday_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='wednesday_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
