# Generated by Django 5.2.4 on 2025-08-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_attended_hours_sectionschedule_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended_hours',
        ),
    ]
