# Generated by Django 5.2.4 on 2025-08-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_attended_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionSchedule',
        ),
    ]
