# Generated by Django 5.2.4 on 2025-08-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_weeklysession_dailyattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklysession',
            name='section',
        ),
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
        migrations.DeleteModel(
            name='WeeklySession',
        ),
    ]
