# Generated by Django 5.2.4 on 2025-08-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_weeklysession_section_delete_dailyattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_hours', models.PositiveSmallIntegerField(default=0)),
                ('tuesday_hours', models.PositiveSmallIntegerField(default=0)),
                ('wednesday_hours', models.PositiveSmallIntegerField(default=0)),
                ('thursday_hours', models.PositiveSmallIntegerField(default=0)),
                ('friday_hours', models.PositiveSmallIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('classIns', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='attendance.class')),
            ],
        ),
    ]
