# Generated by Django 4.0.3 on 2025-08-08 14:13

from django.db import migrations, models

def remove_tardy_data(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')  # use your real app name
    # Convert all old 'tardy' (2) and 'absent' (3) to new 'absent' (2)
    Attendance.objects.filter(type='2').update(type='2')  # tardy -> absent
    Attendance.objects.filter(type='3').update(type='2')  # absent -> absent

class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_class_course'),  # replace with your actual last migration
    ]

    operations = [
        migrations.RunPython(remove_tardy_data),  # << This is the missing part
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(
                choices=[('1', 'Present'), ('2', 'Absent')],
                max_length=250
            ),
        ),
    ]
