# Generated by Django 5.2.4 on 2025-08-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_attended_hours_sectionschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionschedule',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attended_hours',
        ),
        migrations.RemoveField(
            model_name='sectionschedule',
            name='classIns',
        ),
        migrations.AddField(
            model_name='sectionschedule',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='attendance.section'),
        ),
        migrations.CreateModel(
            name='SectionDailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='attendance.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attendance', to='attendance.student')),
            ],
            options={
                'ordering': ['-date', 'student_id'],
                'unique_together': {('student', 'section', 'date')},
            },
        ),
    ]
