# Generated by Django 5.2.4 on 2025-08-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_rename_date_added_sectionschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.section'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
