# Generated by Django 5.2.4 on 2025-08-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_attendance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
