# Generated by Django 5.2.4 on 2025-08-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_remove_course_description_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
