# Generated by Django 5.2.4 on 2025-08-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(max_length=250),
        ),
    ]
